services:
  llama-cpp-rpc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: llama-cpp-rpc
    restart: unless-stopped
    ports:
      - "50052:50052"
    entrypoint: ["/app/rpc-server"]
    command: ["-c", "--host", "0.0.0.0", "--port", "50052"]
